### PR TITLE
Fix ambigous alias

### PR DESCRIPTION
**Pull request by RazvanN7**
This currently blocks : https://github.com/dlang/dmd/pull/6676

### CODE REVIEW

**Comment by wilzbach** [comment]
- `ApplyLeft` was added in 2.071: https://docarchives.dlang.io/v2.071.0/phobos/std_meta.html#.ApplyLeft
- As usual it would be great if this gets tagged with a new git tag after being merged. Thanks!

**Comment by andralex** [comment]
ping @BlackEdder please merge by Feb 2nd so we keep this project on the regression tester list. Thanks!

**Comment by wilzbach** [comment]
Actually our policy is to have a reaction time within three days and that already passed. I will make a PR to dlang/ci and @BlackEdder can simply revert it once this has been fixed.

@BlackEdder you can always move your project to dlang-community, s.t. such maintenance work can be taken care of without delay (or simply give a couple of trustworthy people from permissions to do so).

**Comment by wilzbach** [comment]
> Actually our policy is to have a reaction time within three days and that already passed. I will make a PR to dlang/ci and @BlackEdder can simply revert it once this has been fixed.

https://github.com/dlang/ci/pull/151

**Comment by wilzbach** [comment]
ping @BlackEdder. If you are busy at the moment, how about moving your project to dlang-community?

**Comment by timotheecour** [comment]
https://github.com/dlang/dmd/pull/7930 will issue an error upon alias X= X

**Comment by BlackEdder** [comment]
Sorry for the delay, last couple of weeks have been quite mental. Didn't know ggplotd was important enough to block dlang

**Pull request merged**
