### PR TITLE
Grid display for plots

### PR DESCRIPTION
**Pull request by SMietzner**
This adds grid drawing capability for plots.

### CODE REVIEW

**Comment by SMietzner** [comment]
TRAVIS:

> The command "if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install libjpeg cairo gtk+3; fi" failed and exited with 1 during .

What is causing this?

**Comment by BlackEdder** [comment]
Sorry, why did you close this?

I haven't had time to look at it yet, but will do so.

**Comment by SMietzner** [comment]
> Sorry, why did you close this?

Because I got more into the code and realized that my general approach was a bit simplistic.
For example I managed to display a grid with dashed lines which looks good on simple data plots. But for density plots the grid is drawn behind the density graph and is therefore not visible. I managed to solve even that, but found the solution to be a bit messy. 
So I will revisit it with a fresh mind soon.

**Comment by BlackEdder** [comment]
> But for density plots the grid is drawn behind the density graph and is therefore not visible.

This kinda sounds how I would expect it to work? Unless the density plot is transparent.

Just as a general pointer, instead of overriding the main plotting function, try the API more like the rest API (e.g. see how Margins are passed [here](https://github.com/BlackEdder/ggplotd#custom-axes-margins-image-size-and-title))

In the end the API should look something like:

```D
bool foreground = false;
gg.put(gridLayout(foreground));
```

That way you also wouldn't have to adapt the gtk file etc.

**Pull request closed without merging**
