### PR TITLE
Axes label angle

### PR DESCRIPTION
**Pull request by burner**
https://github.com/BlackEdder/ggplotd/issues/60

axes

```D
    // Setting range and label for xaxis
    gg.put( xaxisRange( 0, 8 ) )
		.put( xaxisLabel( "My xlabel" ) )
		.put( xaxisLabelAngle( 1.57 ) );
```

TODO:
* Radian to Degree

### CODE REVIEW

**Comment by BlackEdder** [comment]
Thank you for this. I notice there is a problem with alignment in one of the ylabels though (0.5)

**Comment by burner** [comment]
that is actually part of the expected output.
the axis offset is set in that test.

**Comment by BlackEdder** [comment]
Thanks! Merged into develop. Will release a new version over the weekend.

**Comment by burner** [comment]
awesome, thank you

**Pull request merged**
